Cyfrin/Updraft

- README.md
Removed the wrong links and added the intended links.
> Fixed links in the README.md file

- courses/security/1-review/11-encoding-function/+page.md
- courses/security/1-review/12-upgradeable-contracts/+page.md
2 typo fixes in the security course content
> Typo fixes

- .github/workflows/update-json.yml
- update_json.js
> dev --> main

- courses/foundry/4-smart-contract-lottery/5-block-timestamp/+page.md
- courses/foundry/4-smart-contract-lottery/9-enum/+page.md
going through the foundry lessons and fixed few typos
> typos fix 

- courses/solidity/3-fund-me/14-libraries/+page.md
import, solidity version and license statement are not in correct order. they are coded under library keyword....
> Fixing Syntax Error in FundMe.sol

- courses/solidity/2-storage-factory/6-interacting-with-contracts-abi/+page.md
Fixed a typo that can confuse people. It took me a minute to fully understand what it was asking and wanted to change it to make it easier for others to understand.
> "fixed typo in the last sentence of the Test Yourself section"

- courses/blockchain-basics/1-basics/8-current-smart-contract-landscape/+page.md
Removed extraneous text from **Decentralization** heading.
> Fix for 8-current-smart-contract-landscape

- courses/security/1-review/11-encoding-function/+page.md
- courses/security/1-review/2-solidity-requisites/+page.md
- courses/security/1-review/6-what-is-erc721/+page.md
- courses/security/1-review/9-fallback-and-receive/+page.md
- courses/security/2-audit/2-the-audit/+page.md
**Note**: Merge https://github.com/Cyfrin/cyfrin-platform/pull/937 first before merging this PR.
> Replace `divs` with updated image tag

- courses/blockchain-basics/1-basics/10-introduction-to-gas/+page.md
- courses/blockchain-basics/1-basics/12-signing-transactions/+page.md
- courses/blockchain-basics/1-basics/13-gas-II/+page.md
- courses/blockchain-basics/1-basics/14-blockchain-fundamentals/+page.md
- courses/blockchain-basics/1-basics/15-l1s-l2s-and-rollups/+page.md
- courses/blockchain-basics/1-basics/18-making-your-first-transaction-on-zksync/+page.md
- courses/blockchain-basics/1-basics/19-why-zksync-is-our-recommended-chain/+page.md
- courses/blockchain-basics/1-basics/4-zksync-sponsorship/+page.md
- courses/blockchain-basics/1-basics/5-what-is-a-blockchain/+page.md
- courses/blockchain-basics/1-basics/9-making-your-first-transaction/+page.md
Fix typos, capitalizations, and formatting
> Written lesson cleanup

- courses/uniswap-v2/2-swap/10-code-walk-get-amounts-in/+page.md
- courses/uniswap-v2/2-swap/14-swap-ex-1/+page.md
- courses/uniswap-v2/2-swap/2-swap-fee/+page.md
Remove AI generated invalid links
Fixes https://github.com/Cyfrin/advanced-defi-2024/discussions/5#discussioncomment-10585322
> Remove AI generated invalid links

- courses/solidity/1-simple-storage/10-mappings/+page.md
- courses/solidity/1-simple-storage/11-deploying/+page.md
- courses/solidity/1-simple-storage/12-zksync-deploying/+page.md
- courses/solidity/1-simple-storage/18-evm-recap/+page.md
- courses/solidity/1-simple-storage/2-best-practices/+page.md
- courses/solidity/1-simple-storage/3-introduction/+page.md
- courses/solidity/1-simple-storage/4-setting-up-your-first-contract/+page.md
- courses/solidity/1-simple-storage/5-basic-types/+page.md
- courses/solidity/1-simple-storage/6-functions/+page.md
- courses/solidity/1-simple-storage/7-arrays-and-structs/+page.md
- courses/solidity/1-simple-storage/8-errors-and-warnings/+page.md
- courses/solidity/1-simple-storage/9-memory-storage-calldata/+page.md
Fix typos, formatting, and clarify sentences in the Solidity Smart Contract Development course (Section 1: Simple Storage)
> Written lesson cleanup: Simple Storage

- courses/solidity/4-ai-prompting/1-ai-and-forums/+page.md
- courses/solidity/4-ai-prompting/2-triage/+page.md
- courses/solidity/4-ai-prompting/5-speedrun/+page.md
Fix typos
Add link to Scaffold-ETH 2
> Written lesson cleanup: AI Prompting

- courses/foundry/2-foundry-fund-me/2-fund-me-project-setup/+page.md
- courses/foundry/2-foundry-fund-me/22-zksync-devops/+page.md
> Written lesson cleanup: Foundry Fund Me

- courses/foundry/3-html-fund-me/1-introduction/+page.md
- courses/foundry/3-html-fund-me/2-setup/+page.md
- courses/foundry/3-html-fund-me/3-metamask/+page.md
- courses/foundry/3-html-fund-me/4-function-selectors/+page.md
Update repository URL and related names (e.g. CLI commands) from -f23 to -cu
Update to "MetaMask" from "Metamask"
> Written lesson cleanup: Foundry Fund Frontend

- courses/foundry/4-smart-contract-lottery/10-the-modulo-operation/+page.md
- courses/foundry/4-smart-contract-lottery/11-implementing the lottery state-enum/+page.md
- courses/foundry/4-smart-contract-lottery/12-lottery-restart-resetting-an-array/+page.md
- courses/foundry/4-smart-contract-lottery/14-the-cei-method-checks-efects-interactions/+page.md
- courses/foundry/4-smart-contract-lottery/15-introduction-to-chainlink-automation/+page.md
- courses/foundry/4-smart-contract-lottery/16-implementing-chainlink-automation/+page.md
- courses/foundry/4-smart-contract-lottery/18-mid-section-recap/+page.md
- courses/foundry/4-smart-contract-lottery/19-tests-and-deploy-the-lotterys-smart-contract-pt1/+page.md
- courses/foundry/4-smart-contract-lottery/2-smart-contract-lottery-project-setup/+page.md
- courses/foundry/4-smart-contract-lottery/20-deploy-script/+page.md
- courses/foundry/4-smart-contract-lottery/21-deploy-a-mock-chainlink-vrf/+page.md
- courses/foundry/4-smart-contract-lottery/22-tests-and-deploy-the-lotterys-smart-contract-p2/+page.md
- courses/foundry/4-smart-contract-lottery/23-setup-the-tests/+page.md
- courses/foundry/4-smart-contract-lottery/3-solidity-style-guide/+page.md
- courses/foundry/4-smart-contract-lottery/4-creating-custom-errors/+page.md
- courses/foundry/4-smart-contract-lottery/5-smart-contracts-events/+page.md
- courses/foundry/4-smart-contract-lottery/6-random-numbers-block-timestamp/+page.md
- courses/foundry/4-smart-contract-lottery/7-random-numbers-introduction-to-chainlink-vrf/+page.md
- courses/foundry/4-smart-contract-lottery/8-implement-the-chainlink-vrf/+page.md
- courses/foundry/4-smart-contract-lottery/9-implementing-vrf-fulfil/+page.md
Fix typos, formatting, and
- Add URL to Solidity docs on Order of Layout style guide
[3-solidity-style-guide/+page.md](https://github.com/Cyfrin/Updraft/compare/dev...gin:gin/cleanup-smart-contract-lottery?expand=1#diff-ae7bfba0e7c889658ca920858df99ff1052f0667ddda33dd75e717211ff29e66)
- Add a note about written lesson is using VRF V2 vs video lesson's VRF V2.5
[8-implement-the-chainlink-vrf/+page.md](https://github.com/Cyfrin/Updraft/compare/dev...gin:gin/cleanup-smart-contract-lottery?expand=1#diff-4d9b3c3dede2aceb5fe4b61be07a33a4326e009946d99f5657ff533503cd8dd1)
- Update written lesson from using VRF V2 to VRF V2.5 to match video lesson
[21-deploy-a-mock-chainlink-vrf/+page.md](https://github.com/Cyfrin/Updraft/pull/226/files#diff-18e3bfb348f5ad1c9d9d03a93b089a217db76f56ec6293e76c2a21c16 …
> Written lesson cleanup: Smart Contract Lottery

- courses/advanced-foundry/3-develop-defi-protocol/1-defi-introduction/+page.md
Remove missing image: https://github.com/Cyfrin/Updraft/issues/237
and fix some typos.
> Remove missing image

- courses/foundry/2-foundry-fund-me/18-introduction-to-storage-optimization/+page.md
"vaule" instead of "value"
I also made a PR for the same thing in the course repository associated to foundry fund me
> fixed typo +page.md 18-introduction-to-storage-optimization

- courses/advanced-foundry/3-develop-defi-protocol/18-defi-handler-stateful-fuzz-tests/+page.md
> Advanced Foundry, DeFi Stablecoin: Add missing "," when inheriting from multiple parents

- courses/advanced-foundry/4-merkle-airdrop/1-introduction/+page.md
- courses/advanced-foundry/4-merkle-airdrop/10-signature-standards/+page.md
- courses/advanced-foundry/4-merkle-airdrop/12-transaction-types-introduction/+page.md
- courses/advanced-foundry/4-merkle-airdrop/13-transaction-types/+page.md
- courses/advanced-foundry/4-merkle-airdrop/14-blob-transactions/+page.md
- courses/advanced-foundry/4-merkle-airdrop/15-understanding-type-113-transactions/+page.md
- courses/advanced-foundry/4-merkle-airdrop/18-test-on-zksync-(optional)/+page.md
- courses/advanced-foundry/4-merkle-airdrop/2-project-setup/+page.md
- courses/advanced-foundry/4-merkle-airdrop/23-deploy-and-claim-on-zksync-local-node-(optional)/+page.md
- courses/advanced-foundry/4-merkle-airdrop/24-deploy-and-claim-on-zksync-sepolia-(optional)/+page.md
- courses/advanced-foundry/4-merkle-airdrop/25-summary/+page.md
- courses/advanced-foundry/4-merkle-airdrop/3-merkle-proofs/+page.md
- courses/advanced-foundry/4-merkle-airdrop/6-merkle-tree-script/+page.md
- courses/advanced-foundry/4-merkle-airdrop/8-deployment-script/+page.md
- courses/advanced-foundry/4-merkle-airdrop/9-adding-signature-verification/+page.md
> Advanced Foundry, Airdrop and Signatures: Fix typos

- courses/advanced-foundry/4-merkle-airdrop/2-project-setup/+page.md
- courses/advanced-foundry/4-merkle-airdrop/4-base-airdrop-contract/+page.md
- courses/advanced-foundry/4-merkle-airdrop/8-deployment-script/+page.md
👍
1. Update `Markle` to `Merkle`
2. Update demo code where there is no `EIP712` library to inherit:
---
3. Update demo's filename `MerkleTree.sol` to `MerkleAirdrop.sol`
---
4. Update to use named imports like the video lesson
> Advanced Foundry, Airdrop and Signatures: Update written lesson setup to be consistent with video

- courses/advanced-foundry/2-how-to-create-an-NFT-collection/7-basic-nft-tests/+page.md
Typos in written lesson and changes needed so code can run according to previous lessons and matching video lesson.
> Advanced Foundry, NFT Section. Fix typos in code examples

- courses/security/2-audit/6-attacks/+page.md
> Smart Contract Security, Section 2: Fix typos

- courses/security/2-audit/3-rekt-test/+page.md
Remove duplicated list in the written lesson, 
and add a missing list item from the Rekt Test list
and update written list format from bullet points to numbered list like Rekt Test
> Smart Contract Security, Section 2: Remove duplicated list

- courses/foundry/4-smart-contract-lottery/25-adding-more-tests/+page.md
Issue link: https://github.com/Cyfrin/Updraft/issues/338
I've analyzed the issue. You use the content in written lesson of video 34 in Section 4 - "Even more tests" instead of content that is used in the video 27 "Adding more tests" .
Actually, you need to refer to the following functions in the written lesson:
```solidity
function testRaffleRevertsWhenYouDontPayEnough() public {
// Arrange
vm.prank(PLAYER);
// Act / Accert
vm.expectRevert(Raffle.Raffle__NotEnoughEthSent.selector);
raffle.enterRaffle();
}
function testRaffleRecordsPlayersWhenTheyEnter() public {
// Arrange
vm.prank(PLAYER);
// Act
raffle.enterRaffle{value: entranceFee}();
// Assert
address playerRecorded = raffle.getPlayer(0);
assert(playerRecorded == PLAYER);
}
```
> rewrite foundry fundamentals section 4 video 27 'adding more tests'

- courses/advanced-foundry/1-How-to-create-an-erc20-crypto-currency/3-erc20-manual-creation/+page.md
While copying / pasting code snippets from the written lesson, I got some issues.
issue link: https://github.com/Cyfrin/Updraft/issues/340
> Advanced-Foundry: Section 1 - Video 3 | Spelling mistakes in code snippets

- courses/advanced-foundry/2-how-to-create-an-NFT-collection/15-svg-deploy/+page.md
Fixing code snippets:
- adding missing semicolons 
- fixing spelling of purse to pure modifier;
> Foundry-advanced: Section 2 - video 16 

- courses/advanced-foundry/2-how-to-create-an-NFT-collection/13-svg-nft-encoding/+page.md
Fixing code snippets in foundry-advanced course section 2 - video 14. _Encoding SVGs to be stored onchain_
> Fixing code snippets in foundry-advanced course section 2 - video 14

- courses/advanced-foundry/3-develop-defi-protocol/11-defi-tests/+page.md
Advanced-foundry: section 3 DeFi - video 13 | minor mistakes
> Advanced-foundry: section 3 DeFi - video 13 | minor mistakes

- courses/advanced-foundry/3-develop-defi-protocol/18-defi-handler-stateful-fuzz-tests/+page.md
advanced-foundry-defi-video-20: missing comma
> advanced-foundry-defi-video-20: missing comma

- courses/advanced-foundry/3-develop-defi-protocol/21-defi-handler-mint-dsc/+page.md
> Advanced-foundry - DeFi protocoll video 24 | fixing minor mistakes

- courses/advanced-foundry/8-daos/5-governor-contract/+page.md
Missing inheritance of TimelockController
> Foundry-advanced: DAO - video 5 | missing inheritance of TimelockController

- audit.py
- Replace bare except with specific FileNotFoundError handling
- Improve string formatting using f-strings
- Clean up unprofessional comments
- Fix spacing inconsistencies
> refactor: Improve code quality in audit.py

- courses/advanced-foundry/5-merkle-airdrop/4-base-airdrop-contract/+page.md
- adding missing infos to code snippets
> Foundry-advanced: Section merkle airdrop - video 4 | adding missing infos to code snippets

- courses/rocket-pool-reth-integration/2-understanding-reth/27-exercise-uniswap-v3-swap-weth-to-reth/+page.md
- courses/rocket-pool-reth-integration/2-understanding-reth/29-exercise-uniswap-v3-swap-reth-to-weth/+page.md
Moved the lesson content in the correct files
> swapWethToReth and swapRethToWeth lessons' content are not in the correct files

- courses/uniswap-v2/6-flash-swap/4-flash-swap-ex/+page.md
- courses/uniswap-v2/6-flash-swap/5-flash-swap-ex-sol/+page.md
This pull request corrects the command to run to execute the test on the flash swap solution, and adds it in the exercise
> strapontin - flash swap exercise cmd to run test

- courses/security/4-puppy-raffle/53-reporting-findings-we-will-cover-later/+page.md
- courses/security/4-puppy-raffle/55-reporting-getActivePlayerIndex-incorrect-for-edge-case/+page.md
- courses/security/4-puppy-raffle/56-reporting-should-follow-cei/+page.md
- courses/security/4-puppy-raffle/64-exercises/+page.md
- courses/security/4-puppy-raffle/65-solodit/+page.md
Added comment about DVD v4 is in Foundry instead of Hardhat.
- courses/security/4-puppy-raffle/64-exercises/+page.md
> Smart Contract Security, Section 4: Minor fixes to written lesson and update on DVD in Foundry

- courses/advanced-foundry/1-How-to-create-an-erc20-crypto-currency/3-erc20-manual-creation/+page.md
- courses/advanced-foundry/2-how-to-create-an-NFT-collection/3-foundry-setup/+page.md
- courses/advanced-foundry/9-security/4-top-tools/+page.md
hey team! I found duplicate words and fixed them.
> docs: remove consecutive duplicate words

- courses/rocket-pool-reth-integration/4-balancer-aura-liquidity/2-aura-intro/+page.md
Adding a space between `-` and the first word of each item will display a list of bullet points
> Rocket Pool rETH Integration, Section 4, Balancer Aura liquidity: Fix Markdown bullet points

- courses/full-stack-web3-development-crash-course/2-html-ts-buy-me-a-coffee/9-simulations/+page.md
https://github.com/Cyfrin/full-stack-web3-cu/discussions/5
> Update create instance publicClient

- courses/rocket-pool-reth-integration/6-eigenlayer-restake/1-eigen-layer-pos-problem/+page.md
Similar to https://github.com/Cyfrin/Updraft/pull/438
> Rocket Pool rETH Integration, Section 6, EigenLayer Restake: Escape dollar-sign in written lesson

- courses/rust-programming-basics/2-rust-intro/3-hello-exercises/+page.md
- courses/rust-programming-basics/2-rust-intro/5-variable-exercises/+page.md
- courses/rust-programming-basics/2-rust-intro/7-function-exercises/+page.md
- courses/rust-programming-basics/3-data-types/11-enum-exercises/+page.md
- courses/rust-programming-basics/3-data-types/13-struct-exercises/+page.md
- courses/rust-programming-basics/3-data-types/15-vector-exercises/+page.md
- courses/rust-programming-basics/3-data-types/17-hash-map-exercises/+page.md
- courses/rust-programming-basics/3-data-types/2-scalar-type-exercises/+page.md
- courses/rust-programming-basics/3-data-types/5-tuple-exercises/+page.md
- courses/rust-programming-basics/3-data-types/9-string-and-str-exercises/+page.md
- courses/rust-programming-basics/4-control-flow/2-if-else-exercises/+page.md
- courses/rust-programming-basics/4-control-flow/4-loop-exercises/+page.md
- courses/rust-programming-basics/4-control-flow/6-match-exercises/+page.md
- courses/rust-programming-basics/4-control-flow/8-if-let-exercises/+page.md
- courses/rust-programming-basics/5-ownership/3-ownership-exercises/+page.md
- courses/rust-programming-basics/5-ownership/5-borrowing-rules-exercises/+page.md
- courses/rust-programming-basics/6-error-handling/2-error-handling-exercises/+page.md
- courses/rust-programming-basics/6-error-handling/4-unwrap-and-expect-exercises/+page.md
- courses/rust-programming-basics/6-error-handling/6-question-operator-exercises/+page.md
- courses/rust-programming-basics/7-module/3-split-modules-into-files-exercises/+page.md
- courses/rust-programming-basics/8-generic-types-and-traits/10-trait-bound-exercises/+page.md
- courses/rust-programming-basics/8-generic-types-and-traits/12-lifetime-exercises/+page.md
- courses/rust-programming-basics/8-generic-types-and-traits/15-iterator-adaptors-exercises/+page.md
- courses/rust-programming-basics/8-generic-types-and-traits/2-generic-types-exercises/+page.md
- courses/rust-programming-basics/8-generic-types-and-traits/4-method-exercises/+page.md
- courses/rust-programming-basics/8-generic-types-and-traits/6-trait-exercises/+page.md
- courses/rust-programming-basics/8-generic-types-and-traits/8-generic-trait-exercises/+page.md
- courses/rust-programming-basics/9-async-await/2-async-await-basic-exercises/+page.md
- courses/rust-programming-basics/9-async-await/5-join-and-select-macros-exercises/+page.md
> [Rust course] Dev --> Main

- courses/security/6-thunder-loan/28-testing-deleting-mappings/+page.md
- courses/security/6-thunder-loan/35-thunderloan-repay-final-functions/+page.md
- Fix typos
- Fix math unit calculation
3e15/1e18 = 0.003 = 0.3%
- Adding a comment to work-around Chisel's bug.
Screenshot showing work-around to Chisel's bug works:
> Smart Contract Security, Section 6, Thunder Loan: Minor fixes to written lessons

- courses/advanced-foundry/4-cross-chain-rebase-token/19-pool-contract/+page.md
[Issue#529](https://github.com/Cyfrin/Updraft/issues/529)
> update ccip version tag
