Cyfrin/Updraft

courses/security/2-audit/1-what-is-an-audit/+page.md

**Purpose of this Pull Request**
I've made a few minor edits to improve the clarity of the documentation. 
**Additional Context**
I've ensured that the formatting and structure of these entries are consistent with the other items in the document.
If any further changes or adjustments are needed, please let me know, and I'll be happy to make them.

docs: minor updates for clarity

---

courses/foundry/2-foundry-fund-me/3-setup-continued/+page.md
courses/foundry/2-foundry-fund-me/4-tests/+page.md

I fixed some typos mainly about function names and import lines.
Also added some lines to describe how to import 'console' contract to make the document more clear.

Fix typos on foundry fundme course

---

courses/foundry/4-smart-contract-lottery/8-modulo/+page.md

**Fix inaccuracy in Lesson 8: Modulo on how the modulo operation is described:**
2 mod 2 equals zero because 2 and 2 divide evenly.
2 mod 3 equals one because there's one left over.
2 mod 6 equals zero because 2 divides into 6 evenly.
2 mod 7 equals one because there's one left over after 2 divides into 7 three times.
Reference to lesson transcript: https://updraft.cyfrin.io/courses/foundry/smart-contract-lottery/solidity-modulo-operation?lesson_format=transcript
**Revised version for clarity:**
2 mod 2 equals zero because 2 and 2 divide evenly.
3 mod 2 equals one because there's one left over.
6 mod 2 equals zero because 6 divides evenly by 2.
7 mod 2 equals one because there's one left over after 7 divides into 2 three times.
When a smaller number is taken modulo by a larger number, the …

Modulo Lesson Notes fix

---

courses/foundry/3-html-fund-me/3-metamask/+page.md

The ethers version 6 methods needed to be updated in getBalance and fund functions.
1.  Instead of `ethers.providers.Web3Provider(window.ethereum)` , it should be `ethers.BrowserProvider(window.ethereum)`
2.  Instead of `ethers.utils.parseEther` , it should be `ethers.parseEther`
3.  Instead of `ethers.utils.formatEther` , it should be `ethers.formatEther` 
related to https://github.com/Cyfrin/html-fund-me-cu/pull/7

Updated ethers api methods in fund and getBalance functions

---

courses/blockchain-basics/1-basics/1-welcome-to-updraft/+page.md
courses/blockchain-basics/1-basics/10-introduction-to-gas/+page.md
courses/blockchain-basics/1-basics/11-how-do-blockchains-work/+page.md
courses/blockchain-basics/1-basics/4-zksync-sponsorship/+page.md

Routes with updated images / line breaks
* https://cyfrin-platform-updraft-lwbci3vm7-cyfrin.vercel.app/courses/blockchain-basics/basics/welcome-to-updraft
* https://cyfrin-platform-updraft-lwbci3vm7-cyfrin.vercel.app/courses/blockchain-basics/basics/introduction-to-gas
* https://cyfrin-platform-updraft-lwbci3vm7-cyfrin.vercel.app/courses/blockchain-basics/basics/how-do-blockchains-work
* https://cyfrin-platform-updraft-lwbci3vm7-cyfrin.vercel.app/courses/blockchain-basics/basics/zksync-sponsorship?lesson_format=transcript

Update a few images with the new inline syntax for testing

---

courses/solidity/2-storage-factory/1-factory-introduction/+page.md
courses/solidity/2-storage-factory/2-setting-up-the-factory/+page.md
courses/solidity/2-storage-factory/3-deploying-a-contract-from-a-contract/+page.md
courses/solidity/2-storage-factory/5-ai-help-ii/+page.md
courses/solidity/2-storage-factory/7-inheritance-in-solidity/+page.md

The image link is broken.
However, when going to the location of where the image should be (https://github.com/Cyfrin/Updraft/tree/main/static/solidity/remix/lesson-3/setting-up), the images are from a previous version of the lesson which does not have the relevant information to what was mentioned in the video lesson.
The written lesson has enough information to match the video lesson.
It is likely okay to remove the broken image.

Written lesson cleanup: Storage Factory

---

courses/solidity/3-fund-me/11-more-solidity-math/+page.md

Swapped **precision** for **accuracy** because within the context of numerical calculation accuracy refers to how close the calculated answer is to the correct value, while precision refers to the number of significant figures used in the result. 
This statement has a high level of precision but low accuracy:
$$pi = 5.464584634564$$
This statement has lower precision but higher accuracy:
$$pi = 3.14$$
The purpose of multiplying before dividing is to calculate a result with higher accuracy.
---
`ethPrice * ethAmount results in 2000e18` is false because:
$$1e18 * 2000e18 = 2000e36$$

Fixed math error and improved language

---

courses/formal-verification/1-horse-store/46-a-note-on-your-new-powers/+page.md

Typo
> contructor payable () {} 
Fixed 
> constructor() payable {}

Formal verification. Lesson 46. Fixed typo

---

courses/solidity/3-fund-me/1-fund-me-intro/+page.md
courses/solidity/3-fund-me/10-getting-prices-from-chainlink/+page.md
courses/solidity/3-fund-me/14-libraries/+page.md
courses/solidity/3-fund-me/15-safemath/+page.md
courses/solidity/3-fund-me/18-sending-eth-from-a-contract/+page.md
courses/solidity/3-fund-me/19-constructor/+page.md
courses/solidity/3-fund-me/2-setup/+page.md
courses/solidity/3-fund-me/20-modifiers/+page.md
courses/solidity/3-fund-me/23-custom-errors/+page.md
courses/solidity/3-fund-me/24-receive-fallback/+page.md
courses/solidity/3-fund-me/25-zksync-plugin-fix/+page.md
courses/solidity/3-fund-me/26-deploying-to-zksync/+page.md
courses/solidity/3-fund-me/27-recap-congratulations/+page.md
courses/solidity/3-fund-me/5-real-world-price-data/+page.md
courses/solidity/3-fund-me/6-mid-lesson-recap/+page.md
courses/solidity/3-fund-me/7-interfaces/+page.md
courses/solidity/3-fund-me/8-ai-help-iii/+page.md
courses/solidity/3-fund-me/9-importing-from-npm-github/+page.md

Fix typos and formatting.
Update "Chainlink Keepers" to "Chainlink Automation (previously known as "Keepers")"
The video lesson is already updated on this name change, but the written lesson has not been updated yet.
https://docs.chain.link/chainlink-automation

Written lesson cleanup: Fund Me

---

courses/advanced-foundry/1-How-to-create-an-erc20-crypto-currency/1-erc20-welcome-to-advanced/+page.md
courses/advanced-foundry/1-How-to-create-an-erc20-crypto-currency/2-erc20-basics/+page.md
courses/advanced-foundry/1-How-to-create-an-erc20-crypto-currency/3-erc20-manual-creation/+page.md
courses/advanced-foundry/1-How-to-create-an-erc20-crypto-currency/4-erc20-open-zeppelin/+page.md
courses/advanced-foundry/1-How-to-create-an-erc20-crypto-currency/5-erc20-deploy-script/+page.md
courses/advanced-foundry/1-How-to-create-an-erc20-crypto-currency/6-erc20-ai-tests-and-recap/+page.md

Fix formatting, demo code, and images
- commit 47cc89e: For this particular image, it is text. I used markdown instead of linking to the image.
https://github.com/Cyfrin/Updraft/blob/main/static/foundry-erc20s/1-erc20-basics/erc20-basics1.png?raw=true
Other images are fixed with the images' new location.

Written lesson cleanup: ERC20

---

courses/advanced-foundry/3-develop-defi-protocol/4-defi-decentralized-stablecoin/+page.md

Added a note in the written lesson about Ownable version 5, because when I followed the lesson's demo code, running `forge build` fails.
This is because lesson uses a previous version of OpenZeppelin's Ownable library. However, for version 5, for our stablecoin project to build without errors, we have to pass in an address in the constructor:
More info at: https://docs.openzeppelin.com/contracts/5.x/access-control#ownership-and-ownable

Advanced Foundry - DeFi Stablecoin: Add note on OpenZeppelin's Ownable version 5

---

courses/advanced-foundry/3-develop-defi-protocol/6-defi-deposit-collateral/+page.md

Added a note in the written lesson about ReentrancyGuard version 5, because when I followed the lesson's demo code, running `forge build` fails.
The reason is because the location for `ReentrancyGuard.sol` has changed to  
`@openzeppelin/contracts/utils/ReentrancyGuard.sol` from
`@openzeppelin/contracts/security/ReentrancyGuard.sol`
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v5.1.0/contracts/utils/ReentrancyGuard.sol

Advanced Foundry - DeFi Stablecoin: Add note on OpenZeppelin's ReentrancyGuard version 5

---

courses/advanced-foundry/3-develop-defi-protocol/13-defi-redeem-collateral/+page.md
courses/advanced-foundry/3-develop-defi-protocol/14-defi-liquidation-setup/+page.md
courses/advanced-foundry/3-develop-defi-protocol/16-defi-leveling-up-testing/+page.md
courses/advanced-foundry/3-develop-defi-protocol/19-defi-handler-deposit-collateral/+page.md
courses/advanced-foundry/3-develop-defi-protocol/23-defi-handler-price-feed/+page.md
courses/advanced-foundry/3-develop-defi-protocol/26-defi-recap/+page.md
courses/advanced-foundry/3-develop-defi-protocol/6-defi-deposit-collateral/+page.md

Fix typos.
For typos that involves demo code, there are:
- `tokeAmountFromDebtCovered` should be `tokenAmountFromDebtCovered`
- `=+` should be `+=`

Advanced Foundry, DeFi Stablecoin: Fix typos

---

courses/advanced-foundry/3-develop-defi-protocol/12-defi-deposit-and-mint/+page.md
courses/advanced-foundry/3-develop-defi-protocol/15-defi-liquidation-refactor/+page.md

In the video lesson, the `depositCollateralAndMintDsc()` function is `external`.
In the written lesson, there is no visibility specifier.
This PR adds `external` to the written lesson.
Screenshot showing video lesson and `external`:
In the video lesson, the `_redeemCollateral()` function is `private`.
In the written lesson, there is no visibility specifier.
This PR adds `private` to the written lesson,
and fix a typo in the variable name `tokeAmountFromDebtCovered` to `tokenAmountFromDebtCovered` (missing `n`).

Advanced Foundry, DeFi Stablecoin: Add missing visibility specifier

---

courses/advanced-foundry/4-merkle-airdrop/20-creating-a-signature/+page.md

Change from invalid address from 
0xf39Fd6e51aad88F6f4ce6aB88272ffFb92266 to valid address from Anvil 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
```
invalid from written lesson:
0xf39Fd6e51aad88F6f4ce6aB88272ffFb92266
valid from Anvil and from video lesson:
0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
```
Maybe some regex removed those characters in the middle of the address in the written lesson like that base64 hash from the NFT lesson?

Advanced Foundry, Airdrop and Signatures: Fix default Anvil key

---

courses/advanced-foundry/4-merkle-airdrop/22-executing-the-anvil-script/+page.md

The written lesson left out the parameter, but the video lesson has it.
The parameter is the 1st default Anvil public key.
Without the parameter, `cast call` fails with an error message saying the function expects 1 parameter.

Advanced Foundry, Airdrop and Signatures: Fix cast call's parameter

---

courses/advanced-foundry/5-upgradeable-smart-contracts/4-uups/+page.md

- space in front of `{` like demo code on other lines
- (line 254) visibility modifier before other modifiers like demo code on other functions

Advanced Foundry, Upgradeable Smart Contracts: Consistent style in demo code

---

courses/foundry/2-foundry-fund-me/18-introduction-to-storage-optimization/+page.md

- Fix incorrect slot number (3 -> 2) in basic variables example
- Fix uint128 byte size calculation (8 -> 16) in complex example
#295

docs: fix storage slot number and uint128 byte size calculations

---

courses/advanced-foundry/5-upgradeable-smart-contracts/4-uups/+page.md
courses/advanced-foundry/5-upgradeable-smart-contracts/5-uups-deploy/+page.md

Pin to latest v4 because in openzeppelin-contracts-upgradeable v5, there are 2 changes that result in the tutorial's demo code to not work and returns error:
1. `__Ownable_init()` takes a parameter in v5
2. `upgradeTo()` deprecated in v5
(Perhaps a note for instructors when they update the lesson in the future 😀)
Latest v4 is v4.9.6
https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/tags
----
Added a line that's missing in written lesson's demo code, so that `forge test` works: Initialize proxy.
The line is in the demo code's GitHub repository but not in the demo code in the written lesson.
https://github.com/Cyfrin/foundry-upgrades-cu/blob/main/script/DeployBox.s.sol#L18

Advanced Foundry, Upgradeable Smart Contracts: Pin version in openzeppelin-contracts-upgradeable and initialize proxy in demo code

---

courses/advanced-foundry/9-security/6-formal-verification/+page.md

First heading has `:`
"Layer 1: Unit Test"
while the following ones do not.
This PR adds `:`, so that it is consistent.

Advanced Foundry, Security: Update headings to be consistent

---

courses/security/3-first-audit/10-exploit-public-data/+page.md
courses/security/3-first-audit/11-recap-ii/+page.md
courses/security/3-first-audit/16-proof-of-code/+page.md
courses/security/3-first-audit/3-details/+page.md
courses/security/3-first-audit/4-cloc/+page.md
courses/security/3-first-audit/7-context/+page.md

1. Fixed some typos.
2. Inserted newline and removed the space in front of `::image{}` that is preventing the image from displaying.

Smart Contract Security, Section 3: Fix typos and image

---

courses/advanced-foundry/3-develop-defi-protocol/11-defi-tests/+page.md

https://updraft.cyfrin.io/courses/advanced-foundry/develop-defi-protocol/test-defi-protocol
```javascript
function testRevertsIfCollateralZero() public {
vm.startPrank(USER);
ERC20Mock(weth).approve(address(dsce), AMOUNT_COLLATERAL);
@> vm.expectRevert(DSCEngine__NeedsMoreThanZero.selector);
dsce.depositCollateral(weth, 0);
vm.stopPrank();
}
```
The error name is directly called instead of calling from contract object.
Contractg object is added `DSCEngine`
```javascript
function testRevertsIfCollateralZero() public {
@> vm.expectRevert(DSCEngine.DSCEngine__NeedsMoreThanZero.selector);
}
```
https://github.com/Cyfrin/Updraft/issues/328

In the written lesson `error name is directly used without accessing it through contract object`

---

courses/advanced-foundry/2-how-to-create-an-NFT-collection/14-svg-nft-flipping/+page.md

Please have a look to openzeppelin-contracts CHANGELOG.md:
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/CHANGELOG.md 
With openzeppelin version 5.0.0 _isApprovedOrOwner was removed in favor of a new `_isAuthorized` function.
_In this logic of removing hidden SLOADs, the `_isApprovedOrOwner` function was removed in favor of a new `_isAuthorized` function. Overrides that used to target the `_isApprovedOrOwner` should now be performed on the `_isAuthorized` function. Calls to `_isApprovedOrOwner` that preceded a call to `_transfer`, `_burn` or `_approve` should be removed in favor of using the `auth` argument in `_update` and `_approve`. This is showcased in `ERC721Burnable.burn` and in `ERC721Wrapper.withdrawTo`._
Adapting this change in the advanced foundry course.

With openzeppelin version 5.0.0 _isApprovedOrOwner was removed in favor of _isAuthorized function

---

courses/advanced-foundry/3-develop-defi-protocol/15-defi-liquidation-refactor/+page.md

- fix _burnDsc: 
parameter is called amountDscToBurn not amount
-  fix call of _redeemCollateral: 
arguments were wrongly used
function sgnature is:
```solidity
_redeemCollateral(address tokenCollateralAddress, uint256 amountCollateral, address from, address to)
```
and not :
```solidity
_redeemCollateral(address from, address to, address tokenCollateralAddress, uint256 amountCollateral )
```

Advanced-foundry - section 3 DeFi - Video 17 | Fix _burnDsc, fix call of _redeemCollateral

---

courses/foundry/1-foundry-simple-storage/16-deploy-a-smart-contract-locally-using-anvil/+page.md

I fixes broken links in the `+page.md` file. The outdated links to Foundry's documentation have been updated to the correct URLs.
- Updated the first link from:  
`https://book.getfoundry.sh/tutorials/best-practices#scripts`  
to:  
`https://book.getfoundry.sh/guides/best-practices#scripts`.
- Updated the second link from:  
`https://book.getfoundry.sh/tutorials/solidity-scripting?highlight=scr#solidity-scripting`  
to:  
`https://book.getfoundry.sh/guides/scripting-with-solidity`.

fix: update broken link +page.md

---

courses/foundry/4-smart-contract-lottery/1-introduction/+page.md

I noticed a small formatting issue in the "NOTE" section, where there was an unnecessary `:br` after the note.
I’ve removed it, making the text cleaner and more readable.

docs: Fixed formatting issue in the "NOTE" section

---

courses/advanced-foundry/3-develop-defi-protocol/22-defi-fuzz-debugging/+page.md

- declare timesMintIsCalled as public because it's called in Invariants.t.sol for logging purposes
- fixing minor mistakes

Foundry-advanced - DeFi protocoll - video 25 | declare timesMintIsCalled as public; fixing minor mistakes

---

courses/advanced-foundry/8-daos/3-setup/+page.md

As in defi section, I've added the same note for Ownable from Openzeppelin:
You can check  here:
https://github.com/Cyfrin/Updraft/blob/main/courses/advanced-foundry/3-develop-defi-protocol/4-defi-decentralized-stablecoin/%2Bpage.md

Foundry-advanced: DAO - video 3 | adding note that Ownable needs an initial owner address

---

courses/advanced-foundry/8-daos/4-governance-tokens/+page.md

-  missing Nonces import 
- renaming MyToken to GovToken

Foundry-advanced: DAO - video 4 | missing import; renaming MyToken to GovToken;

---

courses/advanced-foundry/8-daos/6-tests/+page.md

- `TimelockController`: Changed the role architecture to use `DEFAULT_ADMIN_ROLE` as the admin for all roles, instead of the bespoke `TIMELOCK_ADMIN_ROLE` that was used previously. This aligns with the general recommendation for `AccessControl` and makes the addition of new roles easier. Accordingly, the `admin` parameter and timelock will now be granted `DEFAULT_ADMIN_ROLE` instead of `TIMELOCK_ADMIN_ROLE`. ([#3799](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3799))

Advanced-foundry: DAO - video 6 | adding note for changed admin role; missing semicolon;

---

courses/intro-python-vyper-smart-contract-development/1-favorites/31-workshop-pt-2/+page.md

- HashMap uses `[]` and not `()`. Vyper compiler errors when using `()`.
- Function with `@view` decorator requires additional decorators, or else Vyper compiler errors.

Introduction to Python and Vyper, Section 1: Fix demo code in written lesson

---

courses/intro-python-vyper-smart-contract-development/2-remix-coffee/13-staticcall/+page.md

Introduction to Python and Vyper, Section 2: Fix character encoding in written lesson

---

courses/rocket-pool-reth-integration/2-understanding-reth/13-exercise-eth-to-reth-exchange-rate/+page.md
courses/rocket-pool-reth-integration/2-understanding-reth/15-exercise-reth-to-eth-exchange-rate/+page.md
courses/rocket-pool-reth-integration/2-understanding-reth/17-exercise-reth-availability/+page.md
courses/rocket-pool-reth-integration/2-understanding-reth/19-exercise-reth-deposit-delay/+page.md
courses/rocket-pool-reth-integration/2-understanding-reth/21-exercise-last-deposit-block/+page.md
courses/rocket-pool-reth-integration/2-understanding-reth/23-exercise-rocket-pool-swap-eth-to-reth/+page.md
courses/rocket-pool-reth-integration/2-understanding-reth/25-exercise-rocket-pool-swap-reth-to-eth/+page.md
courses/rocket-pool-reth-integration/2-understanding-reth/27-exercise-uniswap-v3-swap-weth-to-reth/+page.md
courses/rocket-pool-reth-integration/2-understanding-reth/29-exercise-uniswap-v3-swap-reth-to-weth/+page.md
courses/rocket-pool-reth-integration/2-understanding-reth/31-exercise-balancer-swap-weth-to-reth/+page.md
courses/rocket-pool-reth-integration/2-understanding-reth/33-exercise-balancer-swap-reth-to-weth/+page.md
courses/rocket-pool-reth-integration/3-aave-flash-leverage/11-exercise-get-max-flash-loan/+page.md
courses/rocket-pool-reth-integration/3-aave-flash-leverage/13-exercise-open-leverage/+page.md
courses/rocket-pool-reth-integration/3-aave-flash-leverage/15-exercise-close-leverage/+page.md
courses/rocket-pool-reth-integration/4-balancer-aura-liquidity/10-exercise-aura-add-liquidity/+page.md
courses/rocket-pool-reth-integration/4-balancer-aura-liquidity/12-exercise-aura-get-reward/+page.md
courses/rocket-pool-reth-integration/4-balancer-aura-liquidity/14-exercise-aura-remove-liquidity/+page.md
courses/rocket-pool-reth-integration/4-balancer-aura-liquidity/6-exercise-balancer-add-liquidity/+page.md
courses/rocket-pool-reth-integration/4-balancer-aura-liquidity/8-exercise-balancer-remove-liquidity/+page.md
courses/rocket-pool-reth-integration/5-reth-nav/3-exercise-reth-nav/+page.md
courses/rocket-pool-reth-integration/6-eigenlayer-restake/10-exercise-eigen-layer-undelegate/+page.md
courses/rocket-pool-reth-integration/6-eigenlayer-restake/12-exercise-eigen-layer-withdraw/+page.md
courses/rocket-pool-reth-integration/6-eigenlayer-restake/14-exercise-eigen-layer-claim-rewards/+page.md
courses/rocket-pool-reth-integration/6-eigenlayer-restake/6-exercise-eigen-layer-deposit/+page.md
courses/rocket-pool-reth-integration/6-eigenlayer-restake/8-exercise-eigen-layer-delegate/+page.md

Example page : https://updraft.cyfrin.io/courses/rocket-pool-reth-integration/understanding-reth/exercise-eth-to-reth-exchange-rate
When clicking on the link, we get a 404 because it's not redirecting to github

Changed links to redirect to github if clicked from Updraft

---

courses/security/7-bridges/21-recon-continued-again/+page.md

I noticed a couple of text issues that needed fixing:
1. Corrected "his one" to "this one" for clarity.
2. Fixed "cannot emphasized" to "cannot emphasize" for grammatical accuracy.

docs: fix minor text typos

---

courses/foundry/3-html-fund-me/3-metamask/+page.md

a typo where "getBalance buttons" was used instead of "getBalance button" in the text.
This has been corrected to properly refer to a single button. Nothing else was affected.

docs: fix typo in getBalance button reference

---

courses/intro-python-vyper-smart-contract-development/2-remix-coffee/16-deploy-parameter/+page.md
courses/intro-python-vyper-smart-contract-development/2-remix-coffee/24-msg-sender/+page.md

In video 24, the demo is done in Remix, so the `truffle` commands are not relevant.
Also, Truffle Frameword had been deprecated in 2023...

Introduction to Python and Vyper, Section 2: Minor fixes in written lesson, and remove wrong CLI commands in lesson demo'ed in Remix

---

courses/blockchain-basics/1-basics/17-blockchain-fundamentals/+page.md

The sentence "you've done great getting his far" had an error, where "his" should be "**this**."
I’ve corrected it to ensure clarity and accuracy.

docs: fixed typo

---

courses/foundry/1-foundry-simple-storage/26-anvil-zksync-updated/+page.md

Command to install `foundryup-zksync` is 
```
curl -L https://raw.githubusercontent.com/matter-labs/foundry-zksync/main/install-foundry-zksync | bash
```
Source:
https://foundry-book.zksync.io/getting-started/installation
If using the old command to install, it returns an error.

Foundry Fundamentals, Section 1: Update foundryup-zksync installation instructions, and fix minor issues in written lesson

---

README.md

Hey! replaced dead link 
https://github.com/cyfrin/updraft/blob/master/LICENSE.txt - old
https://github.com/Cyfrin/Updraft/blob/main/LICENSE - new

replace broken link LICENSE in README.md

---

courses/formal-verification/1-horse-store/17-opcodes-recap/+page.md

just cleaned up a small typo in the docs. there was an extra "we" in this sentence:  
*"When sending data to a smart contract, we we introduced the concept of calldata."*  
now it's just:  
*"When sending data to a smart contract, we introduced the concept of calldata."*  
simple fix to make things sound better!

docs: fix redundant "we" in the sentence explaining calldata

---

courses/rocket-pool-reth-integration/2-understanding-reth/1-eth-staking/+page.md

Escape dollar-sign to display the `$` symbol correctly in written lesson.
Screenshot of https://updraft.cyfrin.io/courses/rocket-pool-reth-integration/understanding-reth/eth-staking?lesson_format=transcript

Rocket Pool rETH Integration, Section 2, Understanding rETH: Escape dollar-sign in written lesson's Markdown

---

courses/advanced-foundry/4-cross-chain-rebase-token/34-cross-chain-message-sucess/+page.md

Written lesson's URL returns error 404 page: https://docs.chain.link/ccip/directory/
Updated URL returns the expected page: https://docs.chain.link/ccip/directory/mainnet

Advanced Foundry, Cross Chain Rebase Token: Update CCIP Directory's URL

---

courses/advanced-foundry/7-account-abstraction/16-advanced-debugging/+page.md

fix: correct keyboard shortcut for stepping backwards in Tip 2
- Updated the main shortcut from 'J' to 'k' to match actual Foundry Forge debugger behavior (k for previous opcode).
- Ensured consistency in the explanation: k steps backward, j steps forward.
- This fixes the previous contradiction and aligns with official documentation to avoid user confusion during revert debugging.

fix: correct k/j shortcut description in Tip 2 for backward stepping

---

courses/chainlink-fundamentals/2-smart-contract-and-solidity-fundamentals/1-introduction-to-solidity/+page.md
courses/chainlink-fundamentals/2-smart-contract-and-solidity-fundamentals/3-testnet-funds/+page.md
courses/chainlink-fundamentals/7-chainlink-functions/2-chainlink-functions-playground/+page.md

Fix typos across multiple +page.md:
- `permenantly` → `permanently`
- `publically` → `publicly`
- `secific` → `specific`
- `publically` → `publicly`

Fix typos across multiple +page.md
